### ISSUE TITLE
Question: Any plans on officially end of life'ing for `http://code.jquery.com/jquery-latest.js`

### ISSUE THREAD

**Issue by Martii** [jquery/jquery.com#121]
Some issues were raised over at jquery/jquery#2940 and worked around at jquery/jquery#2943 and our organizations and other corps are wondering if there might be a more permanent solution... and appears to have been misplaced and should probably be brought here.

1. Return a simple script saying it's end-of-lifed?
2. Adding in a "nag message", whether `console.warn`, `alert` saying "deprecated" or such?
3. Something else more permanent than a deprecated frozen state? ...

Thank you for the consideration and feedback.

**Comment by gnarf** [comment]
We can not remove this file.

It's not possible.

It would literally break millions of web pages in a few seconds if we did.

We can not add alerts warning of deprecations to these files.

We will forever bear this poor version of jquery-latest.js that is there because it was there, and is used by millions of web page visitors a day.

There was a great blog post about this two years ago by dave: http://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/

We made this choice shortly after google locked their old "latest version" url: https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js at version 1.11.1 and stopped updating it.

We decided to lock at the same version because 1.12 reduced compatibility.

Thanks for reporting this, but please understand that when you have literally millions of hits a day to a url, you can't just "nag message" the entire internet, or it will yell at you.
