### ISSUE TITLE
Vulnerable Version of Jquery on bugs.jquery.com

### ISSUE THREAD

**Issue by mccabe615** [jquery/jquery.com#138]
There seems to be a vulnerable version of Jquery running on bug.jquery.com.[1] 1.7.2 is in use that has a known security vulnerability.[2] It is in use on this [page](https://bugs.jqueryui.com/ticket/8859) I did not discover a way to exploit this issue so XSS is not necessarily present although my testing was limited.

[1]https://bugs.jqueryui.com/chrome/common/js/jquery.js
[2]https://bugs.jquery.com/ticket/11290

**Comment by timmywil** [comment]
XSS vulnerabilities are always present. Ultimately, it is up to the user to sanitize user input. We do our best to guard against these vulnerabilities, but we cannot guard against all of them. The user will always have the power to let something through. That said, I recommend upgrading to later version.

**Comment by dmethvin** [comment]
Also, the tracker on bugs.jquery.com is basically archived at this point and we don't add anything new. That means attacks depending on stored XSS for example are not possible since you can'd add new tickets. Reflected XSS might still be possible but you'd need to find an attack vector where we actually do `$(window.location.hash)` and I don't see one. There is only one use of the hash, it's in https://bugs.jquery.com/chrome/common/js/search.js and it's used safely AFAICT.

**Comment by mgol** [comment]
The tracker https://bugs.jqueryui.com is still used, though.

I agree with the rest of the points; the XSS vulnerability can only be
exploited if we blindly wrapped user input in $(), as long as we're not
doing that, we shpuld be safe.

That doesn't change the fact it'd be better to upgrade jQuery there but not
for security reasons but just to stay current.


-- 
Michał Gołębiowski

**Comment by mccabe615** [comment]
Thanks for the feedback all. I agree with the sentiments. It would be worth upgrading to the latest version in case a change gets implemented that causes a vulnerability.

Also, a very useful tool for these issues is retire.js

http://retirejs.github.io/retire.js/
