### ISSUE TITLE
HTML syntax error on all jquery sites

### ISSUE THREAD

**Issue by IsibisiDev** [jquery/jquery.com#183]
I recently noticed an html syntax error on all jquery sites, including the QUnitJS site, contribute.jquery.org, learn.jquery.com and jquery.org to this line:
`<!--[if IE 9 ]><html class="no-js ie ie9 lte9>"`

**Comment by dmethvin** [comment]
Yep,this looks like a real syntax error, although it would only occur on IE9 browsers.

**Comment by timmywil** [comment]
Afaik, this is intentional to allow for adding ie classes to the HTML tag without the need for JavaScript. This is obviously less common these days with people leaving behind old IE, but it was a common trick back in the day. Point is, we may not want to drop it until we are ready to officially drop old IE on the jQuery sites.

**Comment by mgol** [comment]
The jQuery site looks broken on IE<9 already and has been that way for a long time. Conditional comments may be needed for IE 9 as well, though (IE 10+ doesn't support them).

**Comment by mgol** [comment]
@timmywil The issue here is real, though. There is a syntax error in the IE 9 part of the `html` tag as the `class` attribute ends with an unescaped `>`.

@IsibisiDev would you like to submit a PR? The code for that is most likely located in https://github.com/jquery/jquery-wp-content

**Comment by timmywil** [comment]
Oh, I didn't notice the `>` inside the quotes.
